name: cookbook_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
   # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.2  # ЭТО ДОЛЖНО БЫТЬ ТУТ
  cloud_firestore: ^4.15.1
  
  # UI и утилиты
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  provider: ^6.1.1  # ДОБАВЬТЕ ЭТУ СТРОКУ
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true