// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNfeSiO2f0huOlrUBJvLLANc7dsVXQXHs',
    appId: '1:775650131142:android:e0f7ade909e31368676bc7',
    messagingSenderId: '775650131142',
    projectId: 'cookbookapp-bda67',
    storageBucket: 'cookbookapp-bda67.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArmGofgFz_Tj4Pq7ZrIHCKt9a2inue-YY',
    appId: '1:775650131142:web:750c624d7c8e73dd676bc7',
    messagingSenderId: '775650131142',
    projectId: 'cookbookapp-bda67',
    authDomain: 'cookbookapp-bda67.firebaseapp.com',
    storageBucket: 'cookbookapp-bda67.firebasestorage.app',
    measurementId: 'G-G7K7S010CQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtfzZ5C47HqWTqIhOYEUs6ucq-NJrVy8I',
    appId: '1:775650131142:ios:db91429ff2a3c87a676bc7',
    messagingSenderId: '775650131142',
    projectId: 'cookbookapp-bda67',
    storageBucket: 'cookbookapp-bda67.firebasestorage.app',
    iosBundleId: 'com.example.cookbookApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtfzZ5C47HqWTqIhOYEUs6ucq-NJrVy8I',
    appId: '1:775650131142:ios:db91429ff2a3c87a676bc7',
    messagingSenderId: '775650131142',
    projectId: 'cookbookapp-bda67',
    storageBucket: 'cookbookapp-bda67.firebasestorage.app',
    iosBundleId: 'com.example.cookbookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArmGofgFz_Tj4Pq7ZrIHCKt9a2inue-YY',
    appId: '1:775650131142:web:4b0c79a79bd455b3676bc7',
    messagingSenderId: '775650131142',
    projectId: 'cookbookapp-bda67',
    authDomain: 'cookbookapp-bda67.firebaseapp.com',
    storageBucket: 'cookbookapp-bda67.firebasestorage.app',
    measurementId: 'G-FX5XFBCEZW',
  );

}